# Generated by Django 6.0 on 2026-06-12 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cuisine', models.CharField(max_length=80)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('delivery_time', models.CharField(default='30–45 min', max_length=40)),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('image_url', models.URLField(blank=True, help_text='External image URL')),
                ('image', models.ImageField(blank=True, help_text='Uploaded image (optional)', null=True, upload_to='restaurants/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'restaurants_restaurant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(help_text='Price in INR (₹)')),
                ('image_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('is_veg', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'restaurants_menuitem',
                'ordering': ['name'],
            },
        ),
    ]
